version: '3'
services:
  srs:
    image: ossrs/srs:3
    ports:
      - 8080:8080
    volumes:
      - ./srs.conf:/usr/local/srs/conf/srs.conf
  app:
    build: ./app
    image: broadcast-app:latest
    ports:
      - 80:80