version: '3'
services:
  srs:
    image: ossrs/srs:3
    volumes:
      - ./srs.conf:/usr/local/srs/conf/srs.conf
    ports:
      - 1935:1935
      - 8080:8080
  app:
    build: .
    image: broadcast-app:latest
    ports:
      - 80:80
    environment:
      - HOST=srs
      - KEY=mykey
      - PORT=80