version: '3'
services:
  srs:
    image: ossrs/srs:3
    volumes:
      - ./srs.conf:/usr/local/srs/conf/srs.conf
  app:
    build: ./app
    image: broadcast-app:latest
    environment:
      - HOST=srs
      - KEY=mykey